### ISSUE TITLE
Error: Cannot find module 'discord.js'

### ISSUE THREAD

**Issue by kintaro829** [jamesconrad/Discord-Voice-Normalizer#13]
Hi,
i'm trying to run the Bot on my raspberry pi and get this error message:

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/Desktop/Discord-Voice-Normalizer/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

I've created a new bot, changed the token id and joined the server with the new bot. I can't find the discord.js file in the directory. Hope you can help me get this bot running.

**Comment by jamesconrad** [comment]
discord.js is one of the dependencies of the project, it should have been setup when you ran `npm install`. If you have not ran `npm install` please do and try again. If you have, and still are getting this error then try running `npm install discord.js`.
If you use yarn it's the same command but instead of npm use yarn.

**Comment by kintaro829** [comment]
Do I need a specific node, nodejs and npm version to run the bot?

Today I've installed a new Raspberry OS (March 2021) with this versions:
node: 10.24.0
nodejs: 10.24.0
npm: 5.8.0

I saw on the net there a newer versions available but i can't install them with sudo apt install nodejs. Only version 10.24.0 is availble for me. If i need newer version i'll find a way to run newer versions of node, nodejs and npm. Let me know which versions are needed for the bot.

With `npm install` i've a new folder called node_modules. I can connect to the server. Everytime i send a command the bot crashes and restart. Maybe because of old versions or wrong persmissions (bot)? Which permissions do i need? (I've copied `....bot&permissions=3165184` into my generated link. I hope that was enough :))

This is the error i get:
Attempting Discord connection...
Ready! Connected to 1 server(s), containing 36 users in total.
Performing module setups...
PrimaryDB not found, attempting creation of new one.
Generating guilds table...
Generating guild_members table...
Generating users table...
Waiting 10s to proceed...
SQLITE_CANTOPEN: unable to open database file
iBlaze's Klinik->fr0stblaze: !help
/home/pi/Desktop/Discord-Voice-Normalizer/index.js:91
    client.channels.cache.get(config.errorReportChannelID).send("```" + err.stack + "```");
                                                          ^

TypeError: Cannot read property 'send' of undefined
    at process.<anonymous> (/home/pi/Desktop/Discord-Voice-Normalizer/index.js:91:59)
    at process.emit (events.js:198:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)

**Comment by jamesconrad** [comment]
Your node and npm versions are fine, and those permissions should be correct.

I've pushed a fix for the main error, make sure you check the sample_config.json after pulling, there is a new field that needs to be put into your config.json (`"enableErrorReportingToChannel": false`) Afterwards you can use `!cid` and set `errorReportChannelID` if you want so it can log to a discord channel aswell as console.

As for SQLLITE_CANTOPEN, ensure there is a primary.db file in the db folder, and it has read/write permissions.

**Comment by kintaro829** [comment]
Hello,

thanks for your support. I think we're nearly done. It runs partially. 
I can join or leave the voice channels. The command `!help` is still not functional (see error log). The Discord log also works fine. :)

```
iBlaze's Klinik->iB2K: !joinvoice
Joined voice channel: iBlaze's Klinik -> Privatzimmer
iBlaze's Klinik->iB2K: !leavevoice
Leaving voice channel: iBlaze's Klinik -> Privatzimmer
	Currently in 0 channels.
iBlaze's Klinik->iB2K: !help
ERROR: 
TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/pi/Desktop/DVN/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/pi/Desktop/DVN/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/pi/Desktop/DVN/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/pi/Desktop/DVN/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/pi/Desktop/DVN/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/pi/Desktop/DVN/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at Help (/home/pi/Desktop/DVN/modules/help.js:56:21)
    at Object.ParseMessage (/home/pi/Desktop/DVN/modules/command.js:100:63)
    at Client.client.on (/home/pi/Desktop/DVN/index.js:65:13)
```

It looks like the primary.db file will only be created when you create the db folder manually (i've changed the permissions in every folder with chown before i've run the bot again). Maybe this is a new feature for the future? Create folder/file if it isn't availabe.

I'll test the functionality (`!normalize` command) and give you feedback. I'm back home in round about 9-10 hours. See ya.


--- edit ---

Here are my results:

```
iB2K:
!normalize

[Bot] DVN:
No valid volume passed, defaulting to 100%
Set the following people to the following volumes:
iB2K -> 100.00% (△0.00dB)
fr0stblaze -> 40.17% (△-13.16dB)

iBlaze2K:
!normalize

[Bot] DVN:
No valid volume passed, defaulting to 100%
Set the following people to the following volumes:
iB2K -> 100.00% (△0.00dB)
fr0stblaze -> 40.19% (△-13.15dB)
```

Looks like it's functional (?) but i dont understand why the user iB2K is everytime @100.00%. Shouldnt it be the user who send the `!normalize` command because the settings are client sided? How do this normalizer work in the background? Maybe I'm misinterpreting the function.

Have a nice day :)

**Comment by jamesconrad** [comment]
The issue !help seems to be related to node.js version, did some digging and apparently you will need to update to at least version 12.

As for normalize, the behavior is as intended, the quietest person (iB2K) is always set to the volume argument passed, with no volume argument it defaults to 100%. This is so you can manually find a good volume for the quietest person in the channel and then have everyone else normalized to that level. The main purpose is so one !normalize command allows everyone in the channel to set the volume of each other user in the channel so everyone talks at the same volume. I'd recommend only using with 2 or more other people in the channel with you, and playing with the arguments listed in !normalize -help.

As for how it works in the background, anytime somebodies microphone is active, it calculates the average volume while they are talking, any samples below the threshold set in config.json (minSampleVoldB, default is 40dB). The sound data is immediately discarded after calculating the average volumes. When !normalize is called, it then just takes the average for each user, does some averaging between all users, then converts to dB and a volume % for a more readable format.

As for the database folder thing, I'll add a fix to generate the folder if it's not found, thanks for pointing it out.

**Comment by kintaro829** [comment]
Thank you very much. I was busy the last day and couldn't reply earlier.

I'll try to get a newer node.js/apm versions on my Raspberry Pi the next days. Hope this will fix the issue and see all availabe options. :)

Thanks for the hint with `!normalize -help`. Haven't known there are more options available. Maybe i would know this feature if the `!help` command would work.
With the new known arguments I'll try it out with 2 or more friends.

**Comment by kintaro829** [comment]
Sorry for my late reply. I still haven't figured out why the bot crashes or don't load if i install a newer node/nodejs version with this script for my Raspberry Pi 3b:
https://github.com/audstanley/NodeJs-Raspberry-Pi

I haven't enough skills in linux. Looks like everything except the `!help` command work.
